# -*- coding: utf-8 -*-
"""Proyecto mineria de datos _ DT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_0-_xtEGdPpt_ExkNnLMLX_exPUZ3_I
"""

from google.colab import files

files.upload()

import pandas as pd

df = pd.read_excel("REPORTE_RECORD_ESTUDIANTIL_ANONIMIZADO.xlsx")
df.head()

df.info()

df.describe().round(3)

df["ESTADO"].value_counts()

df["DESERCION"] = df["ESTADO"].apply(
    lambda x: 1 if x == "REPROBADA" else 0
)
df["DESERCION"].value_counts()

columnas_modelo = ["ASISTENCIA", "NO. VEZ", "NIVEL"]

X = df[columnas_modelo]
y = df["DESERCION"]
X.describe().round(3)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced")

model.fit(X_train, y_train)

from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

import pandas as pd

importancias = model.feature_importances_

pd.DataFrame({
    "Variable": columnas_modelo,
    "Importancia": importancias
}).sort_values(by="Importancia", ascending=False)

import joblib

joblib.dump(model, "modelo_desercion.pkl")
joblib.dump(scaler, "scaler.pkl")

from google.colab import files

files.download("modelo_desercion.pkl")
files.download("scaler.pkl")